security:
#password cf client will use when interacting with broker
  user.password: ${user.password}
broker.store:
  node: ${yarnbrk.space:/yarnbrk_space}
yarn:
  provided.params: ${hadoop.provided.params:{}}
  brokerusername: cf
  brokeruserpass: cf1
cf:
  #name of service in cloud foundry catalog
  servicename: ${cf.catalog.servicename:yarn}
  #id of service in cloud foundry catalog
  serviceid: ${cf.catalog.serviceid:yarn}
  #id of base plan in cloud foundry catalog
  baseId: ${BASE_GUID:}
kerberos:
  kdc: ${krb.kdc.host:}
  realm: ${krb.realm:}
metadata:
  imageUrl: ${IMAGE_URL:}
