security:
#password cf client will use when interacting with broker
  user.password: ${user.password}
yarn:
  provided.params: ${hadoop.provided.params:{}}
cf:
  #name of service in cloud foundry catalog
  servicename: ${cf.catalog.servicename:yarn}
  #id of service in cloud foundry catalog
  serviceid: ${cf.catalog.serviceid:yarn}
  #id of base plan in cloud foundry catalog
  baseId: ${BASE_GUID:}
metadata:
  imageUrl: ${IMAGE_URL:}
